server:
  port: 8080

spring:
  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /mall # rabbitmq的虚拟host
    username: guest
    password: guest
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
